language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - TWINE_USERNAME=garrettwrong
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py27-cover,codecov,extension-coveralls,coveralls
      python: '2.7'
    - env:
        - TOXENV=py27-nocov
        - WHEEL_MANYLINUX1=cp27
        - WHEEL_PATH=wheelhouse
      python: '2.7'
    - env:
        - TOXENV=py35-cover,codecov,extension-coveralls,coveralls
      python: '3.5'
    - env:
        - TOXENV=py35-nocov
        - WHEEL_MANYLINUX1=cp35
        - WHEEL_PATH=wheelhouse
      python: '3.5'
    - env:
        - TOXENV=py36-cover,codecov,extension-coveralls,coveralls
      python: '3.6'
    - env:
        - TOXENV=py36-nocov
        - WHEEL_MANYLINUX1=cp36
        - WHEEL_PATH=wheelhouse
      python: '3.6'
    - env:
        - TOXENV=py37-cover,codecov,extension-coveralls,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
        - WHEEL_MANYLINUX1=cp37
        - WHEEL_PATH=wheelhouse
      python: '3.7'
    - env:
        - TOXENV=py38-cover,codecov,extension-coveralls,coveralls
      python: '3.8'
    - env:
        - TOXENV=py38-nocov
        - WHEEL_MANYLINUX1=cp38
        - WHEEL_PATH=wheelhouse
      python: '3.8'
    - env:
        - TOXENV=pypy-cover,codecov,extension-coveralls,coveralls
      python: 'pypy'
    - env:
        - TOXENV=pypy-nocov
      python: 'pypy'
    - env:
        - TOXENV=pypy3-cover,codecov,extension-coveralls,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - |
    (
    set -eux
    if [[ -n ${WHEEL_MANYLINUX1:-} ]]; then
      docker run --rm --user $UID -itv $(pwd):/code ionelmc/manylinux $WHEEL_MANYLINUX1
      tox --installpkg $WHEEL_PATH/*.whl -v
    else
      tox -v
    fi
    if [[ -n ${WHEEL_PATH:-} ]]; then
      twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $WHEEL_PATH/*.whl
    fi
    )
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
