FROM nvidia/cuda:10.2-devel-centos7

# Setup the base system, this is probably oversight by NVIDIA maintainer
RUN yum group install "Development Tools" -y
RUN yum install epel-release -y
RUN yum install cmake3 -y
RUN yum install python36 python36-devel -y
RUN python3.6 -m ensurepip
# Note, numpy 1.20rc was being attempted and failing... I don't need that...
RUN pip3 install 'numpy<1.20'
